# configs/datasets.yaml
datasets:
  - name: SIMSAMU
    path: "medkit/simsamu"
    data_dir:
    split: "train"
  - name: WMT16
    path: "qanastek/WMT-16-PubMed"
    data_dir: "en-fr"
    split: "train"
  - name: DEFT2021
    path: "DrBenchmark/DEFT2021"
    data_dir: 
    split: ["train", "validation", "test"]
