datasets:
  # From HuggingFace 
  - source: WMT16
    path: "qanastek/WMT-16-PubMed"
    subset: "en-fr"
    source_split: "train"
    target_split: 
    commercial_use: True
    comment: ""
  - source: DEFT2021
    path: "DrBenchmark/DEFT2021"
    subset:
    source_split: ["train", "validation", "test"]
    target_split:     
    commercial_use: True
    comment: ""
  - source: FRENCHMEDMCQA
    path: "qanastek/frenchmedmcqa"
    subset:
    source_split: ["train", "validation", "test"]
    target_split:     
    commercial_use: True
    comment: ""
  # From NACHOS
  - source: HAL
    path: "datasets/HAL"
    subset: "NACHOS"
    source_split:
    target_split: 
    commercial_use: True
    comment: ""
  - source: "HAS"
    path: "datasets/HAS"
    subset: "NACHOS"
    source_split:
    target_split: 
    commercial_use: True
    comment: ""
  - source: "WIKIPEDIA"
    path: "datasets/WIKIPEDIA"
    subset: 
    source_split:
    target_split: 
    commercial_use: True
    comment: ""
  - source: "EMEA_V3"
    path: "datasets/EMEA-V3"
    subset: "NACHOS"
    source_split:
    target_split: 
    commercial_use: True
    comment: ""
  - source: "QUAERO"
    path: "datasets/Quaero"
    subset: "NACHOS"
    source_split:
    target_split: 
    commercial_use: True
    comment: ""
  - source: "BDPM"
    path: "datasets/DBPM"
    subset: "NACHOS"
    source_split:
    target_split: 
    commercial_use: True
    comment: ""
  - source: "ECDC_TM"
    path: "datasets/ECDC"
    subset: "NACHOS"
    source_split:
    target_split: 
    commercial_use: True
    comment: ""
  - source: "QUALISCOPE"
    path: "datasets/ScopeSanteQualité"
    subset: "NACHOS"
    source_split:
    target_split: 
    commercial_use: True
    comment: ""
  - source: "CNEDIMTS"
    path: "datasets/CNEDiMTS"
    subset: "NACHOS"
    source_split:
    target_split: 
    commercial_use: True
    comment: ""
  - source: "WMT18_MEDLINE"
    path: "datasets/WMT-18-Medline"
    subset: "NACHOS"
    source_split:
    target_split: 
    commercial_use: False
    comment: ""
  - source: "ISTEX"
    path: "datasets/ISTEX"
    subset: "NACHOS"
    source_split:
    target_split: 
    commercial_use: True
    comment: ""
  - source: "CERIMES"
    path: "datasets/Cerimes"
    subset: "NACHOS"
    source_split:
    target_split: 
    commercial_use: True
    comment: ""
  - source: "CLEAR"
    path: "datasets/CLEAR"
    subset: "NACHOS"
    source_split:
    target_split: 
    commercial_use: False
    comment: ""
  - source: "ANSES_RCP"
    path: "datasets/ANSES_RCP"
    subset: "NACHOS"
    source_split:
    target_split: 
    commercial_use: False
    comment: ""
  - source: "ANSES_SAISINE"
    path: "datasets/ANSES_SAISINE"
    subset: "NACHOS"
    source_split:
    target_split: 
    commercial_use: False
    comment: ""
  - source: "E3C"
    path: "datasets/E3C-Corpus-2.0.0-French"
    subset: "NACHOS"
    source_split:
    target_split: 
    commercial_use: False
    comment: ""
  # From dumps
  - source: MANTRA_GSC
    path: "datasets/mantra_gsc" # local path
    subset: "French"
    source_split: "train"
    target_split: 
    commercial_use: True
    comment: ""
  - source: CAS
    path: "datasets/cas" # local path
    subset: "French"
    source_split: "train"
    target_split: 
    commercial_use: False
    comment: ""
  - source: FRASIMED
    path: "datasets/frasimed" # local path
    subset: "French"
    source_split: "train"
    target_split: 
    commercial_use: False
    comment: ""
  - source: PXCORPUS
    path: "datasets/pxcorpus" # local path
    subset: "French"
    source_split: "train"
    target_split: 
    commercial_use: False
    comment: ""
  - source: MQC
    path: "datasets/mqc" # local path
    subset: "French"
    source_split: "train"
    target_split: 
    commercial_use: False
    comment: ""
